name: Ruff Linter

on:
  pull_request:
  push:
    branches:
    tags-ignore:
      - '**'
    paths:
      - '**/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install ruff
          echo "RUFF_VERSION=$(ruff --version)" >> "${GITHUB_ENV}"

      - name: Runing Ruff ${{ env.RUFF_VERSION }}
        run: ruff check --output-format=github .
